### PR TITLE
Jk suggestions

### PR DESCRIPTION
**Pull request by garlandcrow**
Made some changes that are a little more "rusty"

### CODE REVIEW

**Comment by garlandcrow** [comment]
Mostly just doing this to get used to the flow of github, but here is where we could discuss changes needed before merging etc. We can reference different commits and lines of code etc.

**Comment by glherrit** [comment]
Changes look good to me! (just practicing I guess)

**Comment by glherrit** [comment]
No sure I have I should have did that??

**Comment by garlandcrow** [comment]
There should be a "merge pull request" button to close this PR and merge in the changes. Sometimes things conflict but nowadays github tells you if there are conflicts beforehand.

**Pull request merged**
